// yamlProcessor.js
const yaml = require('js-yaml');
const Handlebars = require('handlebars');
const { format } = require('date-fns');
const path = require('path');
const { createOrUpdateFileOnGitHub } = require('./github');
const { executeAiGenerationTasks } = require('./langchain');

// Slugify a filename: lowercase, hyphens, no spaces or special chars, preserve extension
function slugifyFilename(filename) {
  const ext = path.extname(filename);
  const base = path.basename(filename, ext);
  const slugged = base
    .toLowerCase()
    .replace(/[_\s]+/g, '-')     // underscores and spaces → hyphens
    .replace(/[^a-z0-9-\.]/g, '') // strip anything that isn't alphanumeric, hyphen, or dot
    .replace(/-+/g, '-')          // collapse multiple hyphens
    .replace(/^-|-$/g, '');       // trim leading/trailing hyphens
  return slugged + ext.toLowerCase();
}

// Build traceability metadata footer (appended to every generated document)
function buildTraceabilityFooter(yamlConfig, inputValues) {
  const now = new Date();
  const dateStr = format(now, "MMMM d, yyyy 'at' h:mm a") + ' UTC';
  const model = process.env.ANTHROPIC_MODEL_NAME || 'claude-sonnet-4-20250514';
  const templateId = yamlConfig.id;
  const templateVersion = yamlConfig.version;
  const study = inputValues.selected_study || inputValues.study_name;
  const maxTokens = process.env.ANTHROPIC_MAX_TOKENS || '8192';

  const lines = ['', '---', '', '## Document Information', '', '| Field | Value |', '|-------|-------|'];

  if (dateStr) lines.push(`| Generated | ${dateStr} |`);
  if (model) lines.push(`| Model | ${model} |`);
  if (templateId && templateVersion) {
    lines.push(`| Template | ${templateId} ${templateVersion} |`);
  } else if (templateId) {
    lines.push(`| Template | ${templateId} |`);
  }
  if (study) lines.push(`| Study | ${study} |`);

  // Source files — comma-separated for <5 files, collapsible for 5+
  const noteFiles = inputValues.selected_note_files;
  if (noteFiles) {
    const files = (Array.isArray(noteFiles) ? noteFiles : [noteFiles]).filter(Boolean);
    if (files.length > 0 && files.length < 5) {
      lines.push(`| Source files | ${files.join(', ')} |`);
    } else if (files.length >= 5) {
      lines.push(`| Source files | <details><summary>${files.length} files</summary>${files.map(f => `<br>${f}`).join('')}</details> |`);
    }
  }

  lines.push(`| Max tokens | ${maxTokens} |`);
  lines.push('');
  lines.push('*Generated by Qori*');
  lines.push('');

  return lines.join('\n');
}

// Generate the output content using Handlebars for different templates
function generateOutputTemplate(outputTemplate, { aiGenerated, ...inputValues }) {
  const template = Handlebars.compile(outputTemplate, { noEscape: true });
  return template({
    ...inputValues,
    current_date: format(new Date(), 'MMMM d, yyyy'),
    current_date_iso: format(new Date(), 'yyyy-MM-dd'),
    ai_generated: aiGenerated,
  });
}

async function processYamlTemplate(rawYamlContent, inputValues, baseFolderEncoded, extraFolder = 'primary-research', aiCheck = false) {
  // 1. Parse the raw YAML content first
  const yamlConfig = yaml.load(rawYamlContent);
  if (!yamlConfig) {
    throw new Error('Failed to parse YAML configuration');
  }

  // 2. Decode base folder
  const baseFolder = decodeURIComponent(baseFolderEncoded);

  // 3. Check if output_template exists
  if (!yamlConfig.output_template) {
    throw new Error('Missing output_template in YAML configuration');
  }

  // 4. Prepare LangChain tasks for AI generation (optional)
  let aiResponses = {};
  if (yamlConfig.ai_generation_tasks && yamlConfig.ai_generation_tasks.length > 0) {
    aiResponses = await executeAiGenerationTasks(yamlConfig.ai_generation_tasks, { ...inputValues, current_date: format(new Date(), 'MMMM d, yyyy'), current_date_iso: format(new Date(), 'yyyy-MM-dd') });
    console.log("🚀 ~ processYamlTemplate ~ aiResponses:", aiResponses)
  } else {
    aiResponses = {};
  }

  // 5. Build the output content using the responses from LLM (if any)
  const outputTemplate = generateOutputTemplate(yamlConfig.output_template, {
    ...inputValues,
    aiGenerated: aiResponses,
  });

  // 6. Generate filename and path from YAML configuration
  const filenameTemplate = (yamlConfig.output_options && yamlConfig.output_options.filename) || 'research_brief.md';
  const filePathTemplate = (yamlConfig.output_options && yamlConfig.output_options.path) || '';

  // Render filename with Handlebars and slugify for clean URLs
  const rawFilename = generateOutputTemplate(filenameTemplate, {
    ...inputValues,
    aiGenerated: aiResponses,
    current_date: format(new Date(), 'MMMM d, yyyy'),
    current_date_iso: format(new Date(), 'yyyy-MM-dd'),
  });
  const filename = slugifyFilename(rawFilename);

  const filePath = generateOutputTemplate(filePathTemplate, {
    ...inputValues,
    aiGenerated: aiResponses,
    current_date: format(new Date(), 'MMMM d, yyyy'),
    current_date_iso: format(new Date(), 'yyyy-MM-dd'),
  });

  // 7. Append traceability metadata footer and push to GitHub
  const footer = buildTraceabilityFooter(yamlConfig, inputValues);
  const fullContent = outputTemplate + footer;
  const fullPath = path.posix.join(baseFolder, extraFolder, filePath, filename);
  const result = await createOrUpdateFileOnGitHub(fullPath, fullContent);
  if (aiCheck) {
    return { result, outputTemplate, aiResponses };
  } else {
    return { result, outputTemplate };
  }
}

module.exports = { processYamlTemplate };
