// yamlProcessor.js
const yaml = require('js-yaml');
const Handlebars = require('handlebars');
const { format } = require('date-fns');
const path = require('path');
const { createOrUpdateFileOnGitHub } = require('./github');
const { executeAiGenerationTasks } = require('./langchain');
const { extractVariables } = require('./variableExtractor');
const { readStudyVariables, writeStudyVariables, mergeVariables, readUpstreamVariables, readDiscoveryVariables, writeDiscoveryVariables, mergeDiscoveryVariables, readUpstreamDiscoveryVariables } = require('./studyVariables');

// Slugify a filename: lowercase, hyphens, no spaces or special chars, preserve extension
function slugifyFilename(filename) {
  const ext = path.extname(filename);
  const base = path.basename(filename, ext);
  const slugged = base
    .toLowerCase()
    .replace(/[_\s]+/g, '-')     // underscores and spaces → hyphens
    .replace(/[^a-z0-9-\.]/g, '') // strip anything that isn't alphanumeric, hyphen, or dot
    .replace(/-+/g, '-')          // collapse multiple hyphens
    .replace(/^-|-$/g, '');       // trim leading/trailing hyphens
  return slugged + ext.toLowerCase();
}

// Build traceability metadata footer (appended to every generated document)
function buildTraceabilityFooter(yamlConfig, inputValues) {
  const now = new Date();
  const dateStr = format(now, "MMMM d, yyyy 'at' h:mm a") + ' UTC';
  const model = process.env.ANTHROPIC_MODEL_NAME || 'claude-sonnet-4-20250514';
  const templateId = yamlConfig.id;
  const templateVersion = yamlConfig.version;
  const study = inputValues.selected_study || inputValues.study_name;
  const maxTokens = process.env.ANTHROPIC_MAX_TOKENS || '8192';

  const lines = ['', '---', '', '## Document Information', '', '| Field | Value |', '|-------|-------|'];

  if (dateStr) lines.push(`| Generated | ${dateStr} |`);
  if (model) lines.push(`| Model | ${model} |`);
  if (templateId && templateVersion) {
    lines.push(`| Template | ${templateId} ${templateVersion} |`);
  } else if (templateId) {
    lines.push(`| Template | ${templateId} |`);
  }
  if (study) lines.push(`| Study | ${study} |`);

  // Source files — comma-separated for <5 files, collapsible for 5+
  const noteFiles = inputValues.selected_note_files;
  if (noteFiles) {
    const files = (Array.isArray(noteFiles) ? noteFiles : [noteFiles]).filter(Boolean);
    if (files.length > 0 && files.length < 5) {
      lines.push(`| Source files | ${files.join(', ')} |`);
    } else if (files.length >= 5) {
      lines.push(`| Source files | <details><summary>${files.length} files</summary>${files.map(f => `<br>${f}`).join('')}</details> |`);
    }
  }

  lines.push(`| Max tokens | ${maxTokens} |`);

  // GET traceability — indicate cascade participation
  if (yamlConfig.emits && yamlConfig.emits.length > 0) {
    lines.push(`| Cascade | Emits ${yamlConfig.emits.length} variable types |`);
  }

  lines.push('');
  lines.push('*Generated by Qori*');
  lines.push('');

  return lines.join('\n');
}

// Generate the output content using Handlebars for different templates
function generateOutputTemplate(outputTemplate, { aiGenerated, ...inputValues }) {
  const template = Handlebars.compile(outputTemplate, { noEscape: true });
  return template({
    ...inputValues,
    current_date: format(new Date(), 'MMMM d, yyyy'),
    current_date_iso: format(new Date(), 'yyyy-MM-dd'),
    ai_generated: aiGenerated,
  });
}

async function processYamlTemplate(rawYamlContent, inputValues, baseFolderEncoded, extraFolder = 'primary-research', aiCheck = false) {
  // 1. Parse the raw YAML content first
  const yamlConfig = yaml.load(rawYamlContent);
  if (!yamlConfig) {
    throw new Error('Failed to parse YAML configuration');
  }

  // 2. Decode base folder
  const baseFolder = decodeURIComponent(baseFolderEncoded);

  // 3. Check if output_template exists
  if (!yamlConfig.output_template) {
    throw new Error('Missing output_template in YAML configuration');
  }

  // 3.5 TRANSFORM PHASE: Read upstream variables if consumes spec exists
  const isDiscoveryScope = yamlConfig.discovery_scope === true;
  if (yamlConfig.consumes && yamlConfig.consumes.length > 0) {
    try {
      const upstream = isDiscoveryScope
        ? await readUpstreamDiscoveryVariables(
            inputValues._discovery_team || '',
            inputValues._discovery_type || '',
            inputValues.topic_slug || '',
            yamlConfig.consumes,
          )
        : await readUpstreamVariables(baseFolder, yamlConfig.consumes);
      if (Object.keys(upstream).length > 0) {
        // Inject upstream variables into inputValues so they're available to Generate prompts
        inputValues.upstream_variables = upstream;

        // Also flatten for direct template access: {{upstream_target_barriers}}
        for (const [key, variable] of Object.entries(upstream)) {
          inputValues[`upstream_${key}`] = typeof variable.value === 'string'
            ? variable.value
            : JSON.stringify(variable.value, null, 2);
        }

        console.log(`✅ Transform: Injected ${Object.keys(upstream).length} upstream variables for ${yamlConfig.id}`);
      }
    } catch (error) {
      console.warn(`⚠️ Transform phase failed for ${yamlConfig.id}, continuing without upstream variables:`, error.message);
      // Continue without upstream variables — Generate still works, just without cascade context
    }
  }

  // 4. Prepare LangChain tasks for AI generation (optional)
  let aiResponses = {};
  if (yamlConfig.ai_generation_tasks && yamlConfig.ai_generation_tasks.length > 0) {
    aiResponses = await executeAiGenerationTasks(yamlConfig.ai_generation_tasks, { ...inputValues, current_date: format(new Date(), 'MMMM d, yyyy'), current_date_iso: format(new Date(), 'yyyy-MM-dd') });
    console.log("🚀 ~ processYamlTemplate ~ aiResponses:", aiResponses)
  } else {
    aiResponses = {};
  }

  // 5. Build the output content using the responses from LLM (if any)
  const outputTemplate = generateOutputTemplate(yamlConfig.output_template, {
    ...inputValues,
    aiGenerated: aiResponses,
  });

  // 6. Generate filename and path from YAML configuration
  const filenameTemplate = (yamlConfig.output_options && yamlConfig.output_options.filename) || 'research_brief.md';
  const filePathTemplate = (yamlConfig.output_options && yamlConfig.output_options.path) || '';

  // Render filename with Handlebars and slugify for clean URLs
  const rawFilename = generateOutputTemplate(filenameTemplate, {
    ...inputValues,
    aiGenerated: aiResponses,
    current_date: format(new Date(), 'MMMM d, yyyy'),
    current_date_iso: format(new Date(), 'yyyy-MM-dd'),
  });
  const filename = slugifyFilename(rawFilename);

  const filePath = generateOutputTemplate(filePathTemplate, {
    ...inputValues,
    aiGenerated: aiResponses,
    current_date: format(new Date(), 'MMMM d, yyyy'),
    current_date_iso: format(new Date(), 'yyyy-MM-dd'),
  });

  // 7. Append traceability metadata footer and push to GitHub IMMEDIATELY
  // Document writes first — user gets their result without waiting for Extract
  const footer = buildTraceabilityFooter(yamlConfig, inputValues);
  const fullContent = outputTemplate + footer;
  const fullPath = path.posix.join(baseFolder, extraFolder, filePath, filename);
  const result = await createOrUpdateFileOnGitHub(fullPath, fullContent);

  // 8. EXTRACT PHASE: Runs AFTER document is written — fully non-blocking
  // User already has their document. Extract + variable write happen in background.
  if (yamlConfig.emits && yamlConfig.emits.length > 0) {
    console.log(`🔄 Extract: Starting extraction for ${yamlConfig.id} (${yamlConfig.emits.length} variables)`);
    (async () => {
      try {
        const extractionResult = await extractVariables(outputTemplate, yamlConfig.emits, inputValues);
        if (!extractionResult) {
          console.warn(`⚠️ Extract phase returned null for ${yamlConfig.id}`);
          return;
        }
        console.log(`🔄 Extract: Got ${Object.keys(extractionResult).length} variables for ${yamlConfig.id}`);

        // Write extracted variables — discovery or study scoped
        if (isDiscoveryScope && inputValues.topic_slug && inputValues._discovery_type && inputValues._discovery_team) {
          const team = inputValues._discovery_team;
          const discoveryVars = await readDiscoveryVariables(team, inputValues._discovery_type);
          const merged = mergeDiscoveryVariables(
            discoveryVars,
            extractionResult,
            inputValues.topic_slug,
            yamlConfig.id,
            yamlConfig.version
          );
          await writeDiscoveryVariables(team, inputValues._discovery_type, merged);
          console.log(`✅ Extract: Wrote discovery variables for ${yamlConfig.id} to ${team}/_discovery/${inputValues._discovery_type}`);
        } else {
          const studyVars = await readStudyVariables(baseFolder);
          const merged = mergeVariables(
            studyVars,
            extractionResult,
            yamlConfig.id,
            yamlConfig.version
          );
          await writeStudyVariables(baseFolder, merged);
          console.log(`✅ Extract: Wrote variables for ${yamlConfig.id} to study-variables.json`);
        }

        // Upsert Postgres index (best effort)
        try {
          const sequelize = require('../database');
          const StudyVariable = sequelize.models.StudyVariable;
          if (StudyVariable) {
            const studyName = inputValues.selected_study || inputValues.study_name;
            for (const [key, variable] of Object.entries(extractionResult)) {
              if (!variable.value) continue;
              const entryCount = Array.isArray(variable.value) ? variable.value.length : 1;
              await StudyVariable.upsert({
                study_name: studyName,
                variable_key: key,
                variable_type: variable._emitSpec?.pool ? 'pool' : 'single',
                source_template: yamlConfig.id,
                source_version: yamlConfig.version,
                value_hash: require('./studyVariables').hashVariables({ [key]: variable.value }),
                entry_count: entryCount,
                is_pool: variable._emitSpec?.pool || false,
                stale: false,
                extracted_at: new Date(),
                updated_at: new Date(),
              }, {
                conflictFields: ['study_name', 'variable_key'],
              });
            }
            console.log(`✅ Extract: Upserted Postgres index for ${yamlConfig.id}`);
          }
        } catch (dbError) {
          console.warn(`⚠️ Postgres index upsert failed (non-blocking):`, dbError.message, dbError.errors?.[0]?.message || '');
        }
      } catch (error) {
        console.error(`❌ Failed to write study variables for ${yamlConfig.id}:`, error.message);
      }
    })();
  }

  if (aiCheck) {
    return { result, outputTemplate, aiResponses };
  } else {
    return { result, outputTemplate };
  }
}

module.exports = { processYamlTemplate };
