/**
 * discoverHandler.ts — /qori-discover slash command
 *
 * Discovery is pre-study research. This command opens a modal,
 * collects a topic + files + discovery type, then routes to the
 * appropriate YAML template. Output lands in _discovery/{type}/
 * in the qori-studies repo (not study-scoped).
 */

import type { AllMiddlewareArgs, SlackCommandMiddlewareArgs, SlackViewMiddlewareArgs, ViewSubmitAction } from '@slack/bolt';
import type { View } from '@slack/types';

import { discoverModal } from '../ui/discoverModal';
import { getConfigRepo, YAML_TEMPLATE_PATH, fetchFileFromRepo, createOrUpdateFileOnGitHub, fetchFileFromRepoByPath } from '../../github';
import { format } from 'date-fns';
import { processYamlTemplate } from '../../yamlProcessor';
import { processSlackFiles } from '../../pdfProcessor';
import { parseDocuments, validateDocuments } from '../../documentParser';

// ─── Types ──────────────────────────────────────────────────────

type DiscoveryTypeKey = 'desk_research' | 'stakeholder_synthesis' | 'survey_synthesis';

interface DiscoveryTypeConfig {
  yaml: string;
  folder: string;
  fileSlug: string;
  label: string;
  filetypes: string[];
}

interface ProcessedFile {
  name: string;
  content: string;
  type: string;
  size: number;
}

interface DocumentInfo {
  name: string;
  content: string;
  type: string;
  size: number;
  [key: string]: unknown;
}

interface ValidationResult {
  isValid: boolean;
  message: string;
}

interface ParsedDocuments {
  structured_format: string;
}

interface UploadedFile {
  id: string;
  name: string;
  mimetype: string;
  url: string;
  url_private?: string;
  [key: string]: unknown;
}

/** Data shape passed to discovery YAML templates. */
interface DiscoveryTemplateInput {
  topic: string;
  effective_topic: string;
  topic_slug: string;
  team: string;
  description: string;
  document_content: string;
  combined_file_content: string;
  _discovery_type: string;
  _discovery_team: string;
  selected_study: string;
  study_name: string;
  // Mechanical document inventory (handler-assembled for Handlebars)
  document_count: number;
  document_names: string[];
  document_types: string[];
  // Survey-specific
  survey_name?: string;
  question_focus?: string;
  survey_files?: UploadedFile[];
  // Stakeholder-specific
  study_channel?: string;
  researcher_contact?: string;
  detected_files?: string;
}

// ─── Constants ──────────────────────────────────────────────────

const DEFAULT_TEAM = 'friends-lab';
function getTeamSlug(): string {
  return process.env.QORI_TEAM_SLUG || DEFAULT_TEAM;
}

const DISCOVERY_TYPES: Record<DiscoveryTypeKey, DiscoveryTypeConfig> = {
  desk_research: {
    yaml: 'desk_research.yaml',
    folder: 'desk-research',
    fileSlug: 'desk-research',
    label: 'Desk research',
    filetypes: ['pdf', 'docx', 'doc', 'txt', 'md'],
  },
  stakeholder_synthesis: {
    yaml: 'stakeholder_synthesis.yaml',
    folder: 'stakeholder-interviews',
    fileSlug: 'stakeholder-synthesis',
    label: 'Stakeholder synthesis',
    filetypes: ['pdf', 'docx', 'doc', 'txt', 'md'],
  },
  survey_synthesis: {
    yaml: 'survey_synthesis.yaml',
    folder: 'survey-synthesis',
    fileSlug: 'survey-synthesis',
    filetypes: ['csv', 'xlsx', 'xls'],
    label: 'Survey synthesis',
  },
};

const DISCOVERY_README = `# Discovery Research

Pre-study discovery research that informs briefs and accumulates as organizational memory across studies.

Discovery answers: _What do we already know? What are the open questions? Who are the stakeholders and what do they need?_

## Folder Structure

\`\`\`
_discovery/
  desk-research/        Desk research artifacts
  stakeholder-interviews/   Stakeholder synthesis artifacts
  survey-synthesis/     Survey synthesis artifacts
\`\`\`

Each artifact is identified by a topic slug. Variables are stored per type in \`.variables/\` subdirectories.

*Generated by Qori*
`;

// ─── Helpers ────────────────────────────────────────────────────

/**
 * Slugify a topic string for use in filenames and paths.
 */
function slugifyTopic(topic: string): string {
  return topic
    .toLowerCase()
    .replace(/[_\s]+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

/**
 * Scaffold {team}/_discovery/ folders in qori-studies if they don't exist.
 */
async function scaffoldDiscoveryFolders(team: string): Promise<void> {
  const readmePath = `${team}/_discovery/README.md`;
  try {
    // @ts-expect-error — pre-existing type mismatch from require() → import migration
    await fetchFileFromRepoByPath(process.env.GITHUB_REPO, readmePath);
    return;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const status = (error as Record<string, unknown>)?.status;
    if (status === 404 || message?.includes('Not Found') || message?.includes('Could not fetch file')) {
      console.log(`📁 Scaffolding ${team}/_discovery/ folders in qori-studies...`);
      await createOrUpdateFileOnGitHub(readmePath, DISCOVERY_README);
      console.log(`✅ ${readmePath} created`);
    } else {
      console.warn(`⚠️ Could not check ${readmePath}, proceeding anyway:`, message);
    }
  }
}

// ─── Command handler ────────────────────────────────────────────

async function discoverHandler({ ack, body, client, command }: SlackCommandMiddlewareArgs & AllMiddlewareArgs): Promise<void> {
  await ack();

  const channelId = command.channel_id;

  try {
    await client.views.open({
      trigger_id: body.trigger_id,
      view: {
        ...discoverModal,
        private_metadata: JSON.stringify({ channelId }),
      } as View,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const detail = (err as Record<string, unknown>)?.data ?? message;
    console.error('Error opening discover modal:', detail);
    await client.chat.postMessage({
      channel: channelId,
      text: '❌ Failed to open the discovery modal. Please try again.',
    });
  }
}

// ─── Submission handler ─────────────────────────────────────────

async function handleDiscoverSubmission({ ack, view, body, client }: SlackViewMiddlewareArgs<ViewSubmitAction> & AllMiddlewareArgs): Promise<void> {
  await ack();

  const values = view.state.values;
  const meta = JSON.parse(view.private_metadata || '{}') as { channelId?: string };
  const { channelId } = meta;
  const userId: string = body.user?.id || '';

  // Extract form values
  const discoveryType = values.discovery_type_block?.discovery_type?.selected_option?.value as string | undefined;
  const topic = values.topic_block?.topic?.value?.trim() as string | undefined;
  const description = values.description_block?.description?.value?.trim() || null;
  const surveyName = values.survey_name_block?.survey_name?.value?.trim() || null;
  const questionFocus = values.question_focus_block?.question_focus?.value?.trim() || null;

  const uploadedFiles: UploadedFile[] = values.file_upload_block?.file_upload?.files?.map((file: { id: string; name: string; mimetype: string; url_private: string }) => ({
    id: file.id,
    name: file.name,
    mimetype: file.mimetype,
    url: file.url_private,
  })) || [];

  const replyChannel: string = channelId || userId;

  // Validate required fields
  if (!discoveryType || !DISCOVERY_TYPES[discoveryType as DiscoveryTypeKey]) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Please select a discovery type.',
    });
    return;
  }

  if (!topic) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Topic is required for discovery research.',
    });
    return;
  }

  if (!slugifyTopic(topic)) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Topic must contain alphanumeric characters.',
    });
    return;
  }

  if (uploadedFiles.length === 0) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Please upload at least one file to analyze.',
    });
    return;
  }

  if (discoveryType === 'survey_synthesis' && !surveyName) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Survey name is required for survey synthesis. Please try again.',
    });
    return;
  }

  const typeConfig = DISCOVERY_TYPES[discoveryType as DiscoveryTypeKey];
  const team = getTeamSlug();
  let topicSlug = slugifyTopic(topic);

  // Duplicate handling
  const dateIso: string = format(new Date(), 'yyyy-MM-dd');
  const expectedFilename = `${topicSlug}-${typeConfig.fileSlug}-${dateIso}.md`;
  const expectedPath = `${team}/_discovery/${typeConfig.folder}/${expectedFilename}`;
  try {
    // @ts-expect-error — pre-existing type mismatch from require() → import migration
    await fetchFileFromRepoByPath(process.env.GITHUB_REPO, expectedPath);
    const timeSuffix: string = format(new Date(), 'HHmm');
    topicSlug = `${topicSlug}-${timeSuffix}`;
    console.log(`⚠️ Discovery file exists at ${expectedPath}, using slug: ${topicSlug}`);
  } catch {
    // File doesn't exist — proceed with original slug
  }

  console.log(`🔍 Discovery: team=${team}, type=${discoveryType}, topic="${topic}", slug="${topicSlug}", files=${uploadedFiles.length}`);

  await client.chat.postMessage({
    channel: replyChannel,
    text: `🔍 Running ${typeConfig.label} for "${topic}"... This may take a minute.`,
  });

  try {
    await scaffoldDiscoveryFolders(team);

    const processedFiles: ProcessedFile[] = await processSlackFiles(uploadedFiles, process.env.SLACK_BOT_TOKEN!);
    const documents: DocumentInfo[] = processedFiles.map((file: ProcessedFile) => ({
      name: file.name,
      content: file.content,
      type: file.type,
      size: file.size,
    }));

    const validation: ValidationResult = validateDocuments(documents);
    if (!validation.isValid) {
      await client.chat.postMessage({
        channel: replyChannel,
        text: `❌ ${validation.message}`,
      });
      return;
    }

    const parsedDocuments: ParsedDocuments = parseDocuments(documents);
    const formattedDocumentContent: string = parsedDocuments.structured_format;

    // Mechanical document inventory for Handlebars rendering
    const documentNames = processedFiles.map((f: ProcessedFile) => f.name);
    const documentTypes = processedFiles.map((f: ProcessedFile) => f.type);

    const data: DiscoveryTemplateInput = {
      topic,
      effective_topic: topic,
      topic_slug: topicSlug,
      team,
      description: description || topic,
      document_content: formattedDocumentContent,
      combined_file_content: formattedDocumentContent,
      _discovery_type: typeConfig.folder,
      _discovery_team: team,
      selected_study: `discovery-${topicSlug}`,
      study_name: topic,
      document_count: processedFiles.length,
      document_names: documentNames,
      document_types: documentTypes,
    };

    // Survey-specific fields
    if (discoveryType === 'survey_synthesis') {
      data.survey_name = surveyName || undefined;
      data.question_focus = questionFocus || '';
      data.survey_files = uploadedFiles;
    }

    // Stakeholder-specific fields
    if (discoveryType === 'stakeholder_synthesis') {
      data.study_channel = replyChannel;
      data.researcher_contact = `<@${userId}>`;
      data.detected_files = documents.map(d => d.name).join('\n- ');
    }

    const file = await fetchFileFromRepo(getConfigRepo(), YAML_TEMPLATE_PATH, typeConfig.yaml);

    const renderedYaml = await processYamlTemplate(
      file.content,
      data,
      '',
      '',
    );

    const url: string = renderedYaml.result.url;

    await client.chat.postMessage({
      channel: replyChannel,
      blocks: [
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `✅ *${typeConfig.label} complete*\n\n*Topic:* ${topic}\n*Type:* ${typeConfig.label}`,
          },
        },
        {
          type: 'actions',
          elements: [
            {
              type: 'button',
              text: { type: 'plain_text', text: 'View on GitHub' },
              style: 'primary',
              url,
              action_id: 'view_discovery_result',
            },
          ],
        },
        {
          type: 'context',
          elements: [
            {
              type: 'mrkdwn',
              text: `Discovery artifact stored in \`${team}/_discovery/${typeConfig.folder}/\``,
            },
          ],
        },
        { type: 'divider' },
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `*Next:* Run \`/qori-brief\` to initiate a study informed by this discovery.`,
          },
        },
      ],
      text: `${typeConfig.label} complete for "${topic}". View: ${url}`,
    });

  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error('Error processing discovery:', error);
    await client.chat.postMessage({
      channel: replyChannel,
      text: `❌ Error running ${typeConfig.label}: ${message}\n\nPlease try again or contact support.`,
    });
  }
}

export {
  discoverHandler,
  handleDiscoverSubmission,
};
