/**
 * discoverHandler.ts — /qori-discover slash command
 *
 * v2.0: Hub-based redesign per docs/qori-discover-redesign-spec.md.
 * - Command opens a sections-with-accessories hub (no input blocks, no submit)
 * - Hub shows existing discovery artifacts + next-step guidance (D1, D2)
 * - Three "Start" buttons open type-specific modals via views.update
 * - Single submission handler reads discoveryType from private_metadata
 *
 * Discovery is pre-study research. Output lands in _discovery/{type}/
 * in the qori-studies repo (not study-scoped).
 */

import type { AllMiddlewareArgs, SlackActionMiddlewareArgs, SlackCommandMiddlewareArgs, SlackViewMiddlewareArgs, BlockAction, ViewSubmitAction } from '@slack/bolt';
import type { View } from '@slack/types';

import { discoverHubModal, DISCOVERY_GUIDANCE_BLOCK_ID, DISCOVERY_ARTIFACTS_BLOCK_ID } from '../ui/discoverHubModal';
import { DISCOVER_TYPE_MODALS } from '../ui/discoverTypeModals';
import { loadDiscoveryArtifacts, type DiscoveryArtifact } from '../../discoveryLoader';
import { formatVariableCategories } from '../../cascadeVariableCategories';
import { getConfigRepo, YAML_TEMPLATE_PATH, fetchFileFromRepo, createOrUpdateFileOnGitHub, fetchFileFromRepoByPath } from '../../github';
import { format } from 'date-fns';
import { processYamlTemplate } from '../../yamlProcessor';
import { processSlackFiles } from '../../pdfProcessor';
import { parseDocuments, validateDocuments } from '../../documentParser';

// ─── Types ──────────────────────────────────────────────────────

type DiscoveryTypeKey = 'desk_research' | 'stakeholder_synthesis' | 'survey_synthesis';

interface DiscoveryTypeConfig {
  yaml: string;
  folder: string;
  fileSlug: string;
  label: string;
  filetypes: string[];
}

interface ProcessedFile {
  name: string;
  content: string;
  type: string;
  size: number;
}

interface DocumentInfo {
  name: string;
  content: string;
  type: string;
  size: number;
  [key: string]: unknown;
}

interface ValidationResult {
  isValid: boolean;
  message: string;
}

interface ParsedDocuments {
  structured_format: string;
}

interface UploadedFile {
  id: string;
  name: string;
  mimetype: string;
  url: string;
  url_private?: string;
  [key: string]: unknown;
}

/** Data shape passed to discovery YAML templates. */
interface DiscoveryTemplateInput {
  topic: string;
  effective_topic: string;
  topic_slug: string;
  team: string;
  description: string;
  document_content: string;
  combined_file_content: string;
  _discovery_type: string;
  _discovery_team: string;
  selected_study: string;
  study_name: string;
  document_count: number;
  document_names: string[];
  document_types: string[];
  survey_name?: string;
  question_focus?: string;
  survey_files?: UploadedFile[];
  study_channel?: string;
  researcher_contact?: string;
  detected_files?: string;
}

interface DiscoverMeta {
  channelId?: string;
  discoveryType?: string;
}

// ─── Constants ──────────────────────────────────────────────────

const DEFAULT_TEAM = 'friends-lab';
function getTeamSlug(): string {
  return process.env.QORI_TEAM_SLUG || DEFAULT_TEAM;
}

const DISCOVERY_TYPES: Record<DiscoveryTypeKey, DiscoveryTypeConfig> = {
  desk_research: {
    yaml: 'desk_research.yaml',
    folder: 'desk-research',
    fileSlug: 'desk-research',
    label: 'Desk research',
    filetypes: ['pdf', 'docx', 'doc', 'txt', 'md'],
  },
  stakeholder_synthesis: {
    yaml: 'stakeholder_synthesis.yaml',
    folder: 'stakeholder-interviews',
    fileSlug: 'stakeholder-synthesis',
    label: 'Stakeholder synthesis',
    filetypes: ['pdf', 'docx', 'doc', 'txt', 'md'],
  },
  survey_synthesis: {
    yaml: 'survey_synthesis.yaml',
    folder: 'survey-synthesis',
    fileSlug: 'survey-synthesis',
    filetypes: ['csv', 'xlsx', 'xls'],
    label: 'Survey synthesis',
  },
};

/** Type-aware next-step guidance for success messages (D2). */
const SUCCESS_GUIDANCE: Record<DiscoveryTypeKey, string> = {
  desk_research: 'Run `/qori-discover` again for stakeholder interviews, or `/qori-brief` to start your study.',
  stakeholder_synthesis: 'Run `/qori-discover` for survey data, or `/qori-brief` to start your study.',
  survey_synthesis: 'Run `/qori-brief` to start your study — all discovery feeds in automatically.',
};

const DISCOVERY_README = `# Discovery Research

Pre-study discovery research that informs briefs and accumulates as organizational memory across studies.

Discovery answers: _What do we already know? What are the open questions? Who are the stakeholders and what do they need?_

## Folder Structure

\`\`\`
_discovery/
  desk-research/        Desk research artifacts
  stakeholder-interviews/   Stakeholder synthesis artifacts
  survey-synthesis/     Survey synthesis artifacts
\`\`\`

Each artifact is identified by a topic slug. Variables are stored per type in \`.variables/\` subdirectories.

*Generated by Qori*
`;

// ─── Helpers ────────────────────────────────────────────────────

function slugifyTopic(topic: string): string {
  return topic
    .toLowerCase()
    .replace(/[_\s]+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

async function scaffoldDiscoveryFolders(team: string): Promise<void> {
  const readmePath = `${team}/_discovery/README.md`;
  try {
    // @ts-expect-error — pre-existing type mismatch from require() → import migration
    await fetchFileFromRepoByPath(process.env.GITHUB_REPO, readmePath);
    return;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const status = (error as Record<string, unknown>)?.status;
    if (status === 404 || message?.includes('Not Found') || message?.includes('Could not fetch file')) {
      console.log(`📁 Scaffolding ${team}/_discovery/ folders in qori-studies...`);
      await createOrUpdateFileOnGitHub(readmePath, DISCOVERY_README);
      console.log(`✅ ${readmePath} created`);
    } else {
      console.warn(`⚠️ Could not check ${readmePath}, proceeding anyway:`, message);
    }
  }
}

// ─── D1: Discovery visibility helpers ──────────────────────────

/** Format artifact list for the hub's visibility section. Max 5, concrete categories. */
function buildArtifactDisplayText(artifacts: DiscoveryArtifact[]): string {
  if (artifacts.length === 0) {
    return '_No discovery research yet. Start with desk research to build your team\'s knowledge base._';
  }

  const shown = artifacts.slice(0, 5);
  const lines = shown.map(a => {
    const varKeys = Object.keys(a.variables);
    const categories = formatVariableCategories(varKeys);
    const dateStr = a.date || '';
    return `${a.icon} ${a.slug}${dateStr ? ` · ${dateStr}` : ''}${categories ? ` · ${categories}` : ''}`;
  });

  if (artifacts.length > 5) {
    lines.push(`_...and ${artifacts.length - 5} more. These all feed into /qori-brief automatically._`);
  } else {
    lines.push('_These feed into /qori-brief automatically._');
  }

  return lines.join('\n');
}

// ─── D2: Next-step guidance ────────────────────────────────────

/** Build guidance text based on which discovery types have artifacts. */
function buildGuidanceText(artifacts: DiscoveryArtifact[]): string {
  const hasDesk = artifacts.some(a => a.type === 'desk-research');
  const hasStakeholder = artifacts.some(a => a.type === 'stakeholder-interviews');
  const hasSurvey = artifacts.some(a => a.type === 'survey-synthesis');

  const key = `${hasDesk ? '1' : '0'}-${hasStakeholder ? '1' : '0'}-${hasSurvey ? '1' : '0'}`;

  const GUIDANCE: Record<string, string> = {
    '0-0-0': '_Start with desk research — reports and background docs build the foundation._',
    '1-0-0': '_Desk research done. Stakeholder interviews add constraints and priorities._',
    '0-1-0': '_Stakeholder context captured. Add desk research for broader grounding._',
    '0-0-1': '_Survey data captured. Add desk research or stakeholder context to round out discovery._',
    '1-1-0': '_Ready for /qori-brief, or add survey data first._',
    '1-0-1': '_Ready for /qori-brief, or add stakeholder interviews for constraints._',
    '0-1-1': '_Ready for /qori-brief, or add desk research for broader grounding._',
    '1-1-1': '_Discovery complete. Run /qori-brief to start your study._',
  };

  return GUIDANCE[key] || '_Discovery in progress. Run /qori-brief when you\'re ready to start your study._';
}

// ─── Command handler ────────────────────────────────────────────

async function discoverHandler({ ack, body, client, command }: SlackCommandMiddlewareArgs & AllMiddlewareArgs): Promise<void> {
  await ack();

  const channelId = command.channel_id;
  const team = getTeamSlug();

  try {
    // Load existing discovery artifacts for visibility + guidance
    let artifacts: DiscoveryArtifact[] = [];
    try {
      artifacts = await loadDiscoveryArtifacts(team);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn('Could not load discovery artifacts for hub:', message);
    }

    // Build dynamic hub blocks — loose typing for Block Kit manipulation
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const blocks: any[] = [...discoverHubModal.blocks];

    // Inject D2 guidance
    const guidanceIdx = blocks.findIndex(b => b.block_id === DISCOVERY_GUIDANCE_BLOCK_ID);
    if (guidanceIdx !== -1) {
      blocks[guidanceIdx] = {
        ...blocks[guidanceIdx],
        elements: [
          {
            type: "mrkdwn",
            text: buildGuidanceText(artifacts),
          },
        ],
      };
    }

    // Inject D1 artifact visibility
    const artifactsIdx = blocks.findIndex(b => b.block_id === DISCOVERY_ARTIFACTS_BLOCK_ID);
    if (artifactsIdx !== -1) {
      blocks[artifactsIdx] = {
        ...blocks[artifactsIdx],
        elements: [
          {
            type: "mrkdwn",
            text: buildArtifactDisplayText(artifacts),
          },
        ],
      };
    }

    await client.views.open({
      trigger_id: body.trigger_id,
      view: {
        ...discoverHubModal,
        blocks,
        private_metadata: JSON.stringify({ channelId } satisfies DiscoverMeta),
      } as View,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const detail = (err as Record<string, unknown>)?.data ?? message;
    console.error('Error opening discover hub:', detail);
    await client.chat.postMessage({
      channel: channelId,
      text: '❌ Failed to open the discovery hub. Please try again.',
    });
  }
}

// ─── Action handler: hub → type-specific modal ─────────────────

async function openDiscoverTypeModal({ ack, body, client }: SlackActionMiddlewareArgs<BlockAction> & AllMiddlewareArgs): Promise<void> {
  await ack();

  if (!('view' in body) || !body.view) {
    console.warn('Discovery type opener received non-modal action context');
    return;
  }

  try {
    const meta = JSON.parse(body.view.private_metadata || '{}') as DiscoverMeta;

    // Extract discovery type from the action value
    const action = (body as any).actions?.[0];
    const discoveryType: string | undefined = action?.value;

    if (!discoveryType || !DISCOVER_TYPE_MODALS[discoveryType]) {
      console.error('Unknown discovery type from action:', discoveryType);
      return;
    }

    const modal = DISCOVER_TYPE_MODALS[discoveryType];

    await client.views.update({
      view_id: body.view.id,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Block Kit types don't align with Slack's View type
      view: {
        ...modal,
        private_metadata: JSON.stringify({
          channelId: meta.channelId,
          discoveryType,
        } satisfies DiscoverMeta),
      } as any as View,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const detail = (err as Record<string, unknown>)?.data ?? message;
    console.error('Error opening discovery type modal:', detail);
  }
}

// ─── Submission handler ─────────────────────────────────────────

async function handleDiscoverSubmission({ ack, view, body, client }: SlackViewMiddlewareArgs<ViewSubmitAction> & AllMiddlewareArgs): Promise<void> {
  await ack();

  const values = view.state.values;
  const meta = JSON.parse(view.private_metadata || '{}') as DiscoverMeta;
  const { channelId, discoveryType } = meta;
  const userId: string = body.user?.id || '';

  const replyChannel: string = channelId || userId;

  // Read discovery type from private_metadata (set by action handler)
  if (!discoveryType || !DISCOVERY_TYPES[discoveryType as DiscoveryTypeKey]) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Discovery type missing. Please try again from /qori-discover.',
    });
    return;
  }

  // Extract form values
  const topic = values.topic_block?.topic?.value?.trim() as string | undefined;
  const description = values.description_block?.description?.value?.trim() || null;
  const surveyName = values.survey_name_block?.survey_name?.value?.trim() || null;
  const questionFocus = values.question_focus_block?.question_focus?.value?.trim() || null;

  const uploadedFiles: UploadedFile[] = values.file_upload_block?.file_upload?.files?.map((file: { id: string; name: string; mimetype: string; url_private: string }) => ({
    id: file.id,
    name: file.name,
    mimetype: file.mimetype,
    url: file.url_private,
  })) || [];

  // Validate required fields
  if (!topic) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Topic is required for discovery research.',
    });
    return;
  }

  if (!slugifyTopic(topic)) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Topic must contain alphanumeric characters.',
    });
    return;
  }

  if (uploadedFiles.length === 0) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Please upload at least one file to analyze.',
    });
    return;
  }

  const typeConfig = DISCOVERY_TYPES[discoveryType as DiscoveryTypeKey];
  const team = getTeamSlug();
  let topicSlug = slugifyTopic(topic);

  // Duplicate handling
  const dateIso: string = format(new Date(), 'yyyy-MM-dd');
  const expectedFilename = `${topicSlug}-${typeConfig.fileSlug}-${dateIso}.md`;
  const expectedPath = `${team}/_discovery/${typeConfig.folder}/${expectedFilename}`;
  try {
    // @ts-expect-error — pre-existing type mismatch from require() → import migration
    await fetchFileFromRepoByPath(process.env.GITHUB_REPO, expectedPath);
    const timeSuffix: string = format(new Date(), 'HHmm');
    topicSlug = `${topicSlug}-${timeSuffix}`;
    console.log(`⚠️ Discovery file exists at ${expectedPath}, using slug: ${topicSlug}`);
  } catch {
    // File doesn't exist — proceed with original slug
  }

  console.log(`🔍 Discovery: team=${team}, type=${discoveryType}, topic="${topic}", slug="${topicSlug}", files=${uploadedFiles.length}`);

  await client.chat.postMessage({
    channel: replyChannel,
    text: `🔍 Running ${typeConfig.label} for "${topic}"... This may take a minute.`,
  });

  try {
    await scaffoldDiscoveryFolders(team);

    const processedFiles: ProcessedFile[] = await processSlackFiles(uploadedFiles, process.env.SLACK_BOT_TOKEN!);
    const documents: DocumentInfo[] = processedFiles.map((file: ProcessedFile) => ({
      name: file.name,
      content: file.content,
      type: file.type,
      size: file.size,
    }));

    const validation: ValidationResult = validateDocuments(documents);
    if (!validation.isValid) {
      await client.chat.postMessage({
        channel: replyChannel,
        text: `❌ ${validation.message}`,
      });
      return;
    }

    const parsedDocuments: ParsedDocuments = parseDocuments(documents);
    const formattedDocumentContent: string = parsedDocuments.structured_format;

    const MIME_LABELS: Record<string, string> = {
      'application/pdf': 'PDF',
      'text/plain': 'Text',
      'text/markdown': 'Markdown',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'Word',
      'application/msword': 'Word',
    };
    const documentNames = processedFiles.map((f: ProcessedFile) => f.name);
    const documentTypes = processedFiles.map((f: ProcessedFile) => MIME_LABELS[f.type] || f.type);

    const data: DiscoveryTemplateInput = {
      topic,
      effective_topic: topic,
      topic_slug: topicSlug,
      team,
      description: description || topic,
      document_content: formattedDocumentContent,
      combined_file_content: formattedDocumentContent,
      _discovery_type: typeConfig.folder,
      _discovery_team: team,
      selected_study: `discovery-${topicSlug}`,
      study_name: topic,
      document_count: processedFiles.length,
      document_names: documentNames,
      document_types: documentTypes,
    };

    // Survey-specific fields
    if (discoveryType === 'survey_synthesis') {
      data.survey_name = surveyName || undefined;
      data.question_focus = questionFocus || '';
      data.survey_files = uploadedFiles;
    }

    // Stakeholder-specific fields
    if (discoveryType === 'stakeholder_synthesis') {
      data.study_channel = replyChannel;
      data.researcher_contact = `<@${userId}>`;
      data.detected_files = documents.map(d => d.name).join('\n- ');
      (data as any).file_list = documents.map(d => d.name);
    }

    const file = await fetchFileFromRepo(getConfigRepo(), YAML_TEMPLATE_PATH, typeConfig.yaml);

    const renderedYaml = await processYamlTemplate(
      file.content,
      data,
      '',
      '',
    );

    const url: string = renderedYaml.result.url;

    // Type-aware next-step guidance (D2)
    const nextStep = SUCCESS_GUIDANCE[discoveryType as DiscoveryTypeKey]
      || 'Run `/qori-brief` to start your study.';

    await client.chat.postMessage({
      channel: replyChannel,
      blocks: [
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `✅ *${typeConfig.label} complete*\n\n*Topic:* ${topic}\n*Type:* ${typeConfig.label}`,
          },
        },
        {
          type: 'actions',
          elements: [
            {
              type: 'button',
              text: { type: 'plain_text', text: 'View on GitHub' },
              style: 'primary',
              url,
              action_id: 'view_discovery_result',
            },
          ],
        },
        {
          type: 'context',
          elements: [
            {
              type: 'mrkdwn',
              text: `Discovery artifact stored in \`${team}/_discovery/${typeConfig.folder}/\``,
            },
          ],
        },
        { type: 'divider' },
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `*Next:* ${nextStep}`,
          },
        },
      ],
      text: `${typeConfig.label} complete for "${topic}". View: ${url}`,
    });

  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error('Error processing discovery:', error);
    await client.chat.postMessage({
      channel: replyChannel,
      text: `❌ Error running ${typeConfig.label}: ${message}\n\nPlease try again or contact support.`,
    });
  }
}

export {
  discoverHandler,
  openDiscoverTypeModal,
  handleDiscoverSubmission,
};
