/**
 * discoverHandler.js — /qori-discover slash command
 *
 * Discovery is pre-study research. This command opens a modal,
 * collects a topic + files + discovery type, then routes to the
 * appropriate YAML template. Output lands in _discovery/{type}/
 * in the qori-studies repo (not study-scoped).
 */
const { discoverModal } = require('../ui/discoverModal');
const { getConfigRepo, YAML_TEMPLATE_PATH, fetchFileFromRepo, createOrUpdateFileOnGitHub, fetchFileFromRepoByPath } = require('../../github');
const { format } = require('date-fns');
const { processYamlTemplate } = require('../../yamlProcessor');
const { processSlackFiles } = require('../../pdfProcessor');
const { parseDocuments, validateDocuments } = require('../../documentParser');

const DEFAULT_TEAM = 'friends-lab';
function getTeamSlug() {
  return process.env.QORI_TEAM_SLUG || DEFAULT_TEAM;
}

// Discovery type → YAML filename + folder slug
const DISCOVERY_TYPES = {
  desk_research: {
    yaml: 'desk_research.yaml',
    folder: 'desk-research',
    fileSlug: 'desk-research',
    label: 'Desk research',
    filetypes: ['pdf', 'docx', 'doc', 'txt', 'md'],
  },
  stakeholder_synthesis: {
    yaml: 'stakeholder_synthesis.yaml',
    folder: 'stakeholder-interviews',
    fileSlug: 'stakeholder-synthesis',
    label: 'Stakeholder synthesis',
    filetypes: ['pdf', 'docx', 'doc', 'txt', 'md'],
  },
  survey_synthesis: {
    yaml: 'survey_synthesis.yaml',
    folder: 'survey-synthesis',
    fileSlug: 'survey-synthesis',
    filetypes: ['csv', 'xlsx', 'xls'],
    label: 'Survey synthesis',
  },
};

// _discovery/ README content for qori-studies repo (written on first scaffold)
const DISCOVERY_README = `# Discovery Research

Pre-study discovery research that informs briefs and accumulates as organizational memory across studies.

Discovery answers: _What do we already know? What are the open questions? Who are the stakeholders and what do they need?_

## Folder Structure

\`\`\`
_discovery/
  desk-research/        Desk research artifacts
  stakeholder-interviews/   Stakeholder synthesis artifacts
  survey-synthesis/     Survey synthesis artifacts
\`\`\`

Each artifact is identified by a topic slug. Variables are stored per type in \`.variables/\` subdirectories.

*Generated by Qori*
`;

/**
 * Slugify a topic string for use in filenames and paths.
 */
function slugifyTopic(topic) {
  return topic
    .toLowerCase()
    .replace(/[_\s]+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

/**
 * Scaffold {team}/_discovery/ folders in qori-studies if they don't exist.
 * Uses the README as a marker — if it exists, scaffolding is done.
 * GitHub API creates intermediate dirs automatically.
 * @param {string} team - team slug
 */
async function scaffoldDiscoveryFolders(team) {
  const readmePath = `${team}/_discovery/README.md`;
  try {
    await fetchFileFromRepoByPath(process.env.GITHUB_REPO, readmePath);
    // README exists — scaffolding already done
    return;
  } catch (error) {
    if (error.status === 404 || error.message?.includes('Not Found') || error.message?.includes('Could not fetch file')) {
      // README doesn't exist — scaffold now
      console.log(`📁 Scaffolding ${team}/_discovery/ folders in qori-studies...`);
      await createOrUpdateFileOnGitHub(readmePath, DISCOVERY_README);
      console.log(`✅ ${readmePath} created`);
    } else {
      // Unexpected error — log but don't block the flow
      console.warn(`⚠️ Could not check ${readmePath}, proceeding anyway:`, error.message);
    }
  }
}

/**
 * Command handler for /qori-discover
 */
async function discoverHandler({ ack, body, client, command }) {
  await ack();

  const channelId = command.channel_id;

  try {
    await client.views.open({
      trigger_id: body.trigger_id,
      view: {
        ...discoverModal,
        private_metadata: JSON.stringify({ channelId }),
      },
    });
  } catch (err) {
    console.error('Error opening discover modal:', err.data || err);
    await client.chat.postMessage({
      channel: channelId,
      text: '❌ Failed to open the discovery modal. Please try again.',
    });
  }
}

/**
 * Modal submission handler for discover_modal
 */
async function handleDiscoverSubmission({ ack, view, body, client }) {
  await ack();

  const values = view.state.values;
  const meta = JSON.parse(view.private_metadata || '{}');
  const { channelId } = meta;
  const userId = body.user?.id || body.user_id;

  // Extract form values
  const discoveryType = values.discovery_type_block?.discovery_type?.selected_option?.value;
  const topic = values.topic_block?.topic?.value?.trim();
  const description = values.description_block?.description?.value?.trim() || null;
  const surveyName = values.survey_name_block?.survey_name?.value?.trim() || null;
  const questionFocus = values.question_focus_block?.question_focus?.value?.trim() || null;

  const uploadedFiles = values.file_upload_block?.file_upload?.files?.map(file => ({
    id: file.id,
    name: file.name,
    mimetype: file.mimetype,
    url: file.url_private,
  })) || [];

  const replyChannel = channelId || userId;

  // Validate required fields
  if (!discoveryType || !DISCOVERY_TYPES[discoveryType]) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Please select a discovery type.',
    });
    return;
  }

  if (!topic) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Topic is required for discovery research.',
    });
    return;
  }

  // Reject topics that produce empty slugs (e.g., all special characters)
  if (!slugifyTopic(topic)) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Topic must contain alphanumeric characters.',
    });
    return;
  }

  if (uploadedFiles.length === 0) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Please upload at least one file to analyze.',
    });
    return;
  }

  // Survey type requires survey_name
  if (discoveryType === 'survey_synthesis' && !surveyName) {
    await client.chat.postMessage({
      channel: replyChannel,
      text: '❌ Survey name is required for survey synthesis. Please try again.',
    });
    return;
  }

  const typeConfig = DISCOVERY_TYPES[discoveryType];
  const team = getTeamSlug();
  let topicSlug = slugifyTopic(topic);

  // Duplicate handling: if file already exists for this slug+date, append -HHMM
  const dateIso = format(new Date(), 'yyyy-MM-dd');
  const expectedFilename = `${topicSlug}-${typeConfig.fileSlug}-${dateIso}.md`;
  const expectedPath = `${team}/_discovery/${typeConfig.folder}/${expectedFilename}`;
  try {
    await fetchFileFromRepoByPath(process.env.GITHUB_REPO, expectedPath);
    // File exists — append timestamp to avoid overwrite
    const timeSuffix = format(new Date(), 'HHmm');
    topicSlug = `${topicSlug}-${timeSuffix}`;
    console.log(`⚠️ Discovery file exists at ${expectedPath}, using slug: ${topicSlug}`);
  } catch {
    // File doesn't exist — proceed with original slug
  }

  console.log(`🔍 Discovery: team=${team}, type=${discoveryType}, topic="${topic}", slug="${topicSlug}", files=${uploadedFiles.length}`);

  // Send processing message
  await client.chat.postMessage({
    channel: replyChannel,
    text: `🔍 Running ${typeConfig.label} for "${topic}"... This may take a minute.`,
  });

  try {
    // Scaffold {team}/_discovery/ if first use
    await scaffoldDiscoveryFolders(team);

    // Process uploaded files
    const processedFiles = await processSlackFiles(uploadedFiles, process.env.SLACK_BOT_TOKEN);
    const documents = processedFiles.map(file => ({
      name: file.name,
      content: file.content,
      type: file.type,
      size: file.size,
    }));

    const validation = validateDocuments(documents);
    if (!validation.isValid) {
      await client.chat.postMessage({
        channel: replyChannel,
        text: `❌ ${validation.message}`,
      });
      return;
    }

    const parsedDocuments = parseDocuments(documents);
    const formattedDocumentContent = parsedDocuments.structured_format;

    // Build data object — varies by discovery type
    const data = {
      topic,
      topic_slug: topicSlug,
      team,
      description: description || topic,
      document_content: formattedDocumentContent,
      combined_file_content: formattedDocumentContent,
      // Internal: used by yamlProcessor to route variable storage
      _discovery_type: typeConfig.folder,
      _discovery_team: team,
      // These fields exist for backward compat with YAML templates that still reference them
      selected_study: `discovery-${topicSlug}`,
      study_name: topic,
    };

    // Survey-specific fields
    if (discoveryType === 'survey_synthesis') {
      data.survey_name = surveyName;
      data.question_focus = questionFocus || '';
      data.survey_files = uploadedFiles;
    }

    // Stakeholder-specific fields
    if (discoveryType === 'stakeholder_synthesis') {
      data.study_channel = replyChannel;
      data.researcher_contact = `<@${userId}>`;
    }

    // Fetch YAML template
    const file = await fetchFileFromRepo(getConfigRepo(), YAML_TEMPLATE_PATH, typeConfig.yaml);

    // Process template with empty base folder and extra folder
    // This makes the full path: _discovery/{type}/{filename}
    const renderedYaml = await processYamlTemplate(
      file.content,
      data,
      '',   // no study base folder
      '',   // no extra folder (path comes from YAML output_options)
    );

    const url = renderedYaml.result.url;

    // Post result to channel
    await client.chat.postMessage({
      channel: replyChannel,
      blocks: [
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `✅ *${typeConfig.label} complete*\n\n*Topic:* ${topic}\n*Type:* ${typeConfig.label}`,
          },
        },
        {
          type: 'actions',
          elements: [
            {
              type: 'button',
              text: { type: 'plain_text', text: 'View on GitHub' },
              style: 'primary',
              url,
              action_id: 'view_discovery_result',
            },
          ],
        },
        {
          type: 'context',
          elements: [
            {
              type: 'mrkdwn',
              text: `Discovery artifact stored in \`${team}/_discovery/${typeConfig.folder}/\``,
            },
          ],
        },
      ],
      text: `${typeConfig.label} complete for "${topic}". View: ${url}`,
    });

  } catch (error) {
    console.error('Error processing discovery:', error);
    await client.chat.postMessage({
      channel: replyChannel,
      text: `❌ Error running ${typeConfig.label}: ${error.message}\n\nPlease try again or contact support.`,
    });
  }
}

module.exports = {
  discoverHandler,
  handleDiscoverSubmission,
};
