/**
 * Discovery Application Service — PLAT-3
 *
 * Extracted from discoverHandler.ts
 * Orchestrates discovery research workflows: document processing,
 * privacy gating, YAML template processing, cascade variable extraction,
 * and discovery folder scaffolding.
 */

import type { ApplicationContext } from '../types/application-context';
import { format } from 'date-fns';
import { assertProjectAccessByActor } from '../services/authorization.service';
import { getProjectById } from '../services/project.service';
import { loadDiscoveryArtifacts, type DiscoveryArtifact } from '../helpers/discoveryLoader';
import { getConfigRepo, YAML_TEMPLATE_PATH, fetchFileFromRepo, createOrUpdateFileOnGitHub, fetchFileFromRepoByPath } from '../helpers/github';
import { processYamlTemplate } from '../helpers/yamlProcessor';
import { parseDocuments, validateDocuments } from '../helpers/documentParser';
import type { VariableContext } from '../helpers/studyVariables';
import { authorizeForModel, scanForPii } from '../services/content-governance.service';

// ─── Input/Output Types ──────────────────────────────────────────

export type DiscoveryTypeKey = 'desk_research' | 'stakeholder_synthesis' | 'survey_synthesis';

export interface DiscoveryInput {
  /** Project context */
  projectId: number;
  projectSlug: string;

  /** Discovery type */
  discoveryType: DiscoveryTypeKey;

  /** Form fields */
  topic: string;
  description: string | null;

  /** Processed document content (already extracted from files) */
  documents: DocumentInput[];

  /** Actor info */
  createdByActorId: string;

  /** Survey-specific fields */
  surveyName?: string;
  questionFocus?: string;
}

export interface DocumentInput {
  name: string;
  content: string;
  type: string;
  size: number;
  [key: string]: unknown;
}

export interface DiscoveryResult {
  /** URL of the generated artifact on GitHub */
  url: string;
  /** Topic slug used */
  topicSlug: string;
  /** Discovery type label */
  typeLabel: string;
  /** Cascade extraction outcome */
  extractionSuccess: boolean;
  extractionVariableCount: number;
}

export interface DiscoveryArtifactInfo {
  slug: string;
  type: string;
  label: string;
  date: string;
  icon: string;
  variableCount: number;
}

export interface PrivacyViolation {
  label: string;
  snippet: string;
}

// ─── Constants ──────────────────────────────────────────────────

interface DiscoveryTypeConfig {
  yaml: string;
  type: string;
  fileSlug: string;
  label: string;
}

const DISCOVERY_TYPES: Record<DiscoveryTypeKey, DiscoveryTypeConfig> = {
  desk_research: {
    yaml: 'desk_research.yaml',
    type: 'desk-research',
    fileSlug: 'desk-research',
    label: 'Desk research',
  },
  stakeholder_synthesis: {
    yaml: 'stakeholder_synthesis.yaml',
    type: 'stakeholder-interviews',
    fileSlug: 'stakeholder-synthesis',
    label: 'Stakeholder synthesis',
  },
  survey_synthesis: {
    yaml: 'survey_synthesis.yaml',
    type: 'survey-synthesis',
    fileSlug: 'survey-synthesis',
    label: 'Survey synthesis',
  },
};

const DISCOVERY_README = `# Discovery Research

Pre-study discovery research that informs briefs and accumulates as organizational memory.

## Contents

Discovery artifacts are stored directly in this folder.

*Generated by Qori*
`;

// ─── Helpers ────────────────────────────────────────────────────

function slugifyTopic(topic: string): string {
  return topic
    .toLowerCase()
    .replace(/[_\s]+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

async function scaffoldDiscoveryFolders(projectSlug: string): Promise<void> {
  const readmePath = `${projectSlug}/00-discovery/README.md`;
  try {
    await fetchFileFromRepoByPath(process.env.GITHUB_REPO!, readmePath);
    return;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const status = (error as Record<string, unknown>)?.status;
    if (status === 404 || message?.includes('Not Found') || message?.includes('Could not fetch file')) {
      await createOrUpdateFileOnGitHub(readmePath, DISCOVERY_README);
    }
  }
}

// ─── List Discovery Artifacts ───────────────────────────────────

export async function listDiscoveryArtifacts(
  ctx: ApplicationContext,
  projectId: number,
): Promise<DiscoveryArtifactInfo[]> {
  await assertProjectAccessByActor(ctx.actor.id, projectId, ctx.organization.id);

  const artifacts = await loadDiscoveryArtifacts(projectId);
  return artifacts.map((a: DiscoveryArtifact) => ({
    slug: a.slug,
    type: a.type,
    label: a.label,
    date: a.date,
    icon: a.icon,
    variableCount: a.variableCount,
  }));
}

// ─── Main Orchestration ─────────────────────────────────────────

export async function executeDiscovery(
  ctx: ApplicationContext,
  input: DiscoveryInput,
): Promise<DiscoveryResult> {
  // Authorization
  await assertProjectAccessByActor(ctx.actor.id, input.projectId, ctx.organization.id);

  const typeConfig = DISCOVERY_TYPES[input.discoveryType];
  if (!typeConfig) {
    throw new Error(`Unknown discovery type: ${input.discoveryType}`);
  }

  if (!input.topic || !slugifyTopic(input.topic)) {
    throw new Error('Topic must contain alphanumeric characters');
  }

  if (input.documents.length === 0) {
    throw new Error('At least one document is required');
  }

  let topicSlug = slugifyTopic(input.topic);

  // Validate documents
  const validation = validateDocuments(input.documents);
  if (!validation.isValid) {
    throw new Error(validation.message);
  }

  // Check for duplicate filename
  const dateIso = format(new Date(), 'yyyy-MM-dd');
  const expectedFilename = `${topicSlug}-${typeConfig.fileSlug}-${dateIso}.md`;
  const expectedPath = `${input.projectSlug}/00-discovery/${expectedFilename}`;
  try {
    await fetchFileFromRepoByPath(process.env.GITHUB_REPO!, expectedPath);
    const timeSuffix = format(new Date(), 'HHmm');
    topicSlug = `${topicSlug}-${timeSuffix}`;
  } catch {
    // File doesn't exist — proceed
  }

  // Load project for problem_statement
  const project = await getProjectById(input.projectId);
  const projectProblemStatement = project?.problem_statement || null;

  // Scaffold discovery folders
  await scaffoldDiscoveryFolders(input.projectSlug);

  // Parse documents
  const parsedDocuments = parseDocuments(input.documents);
  const formattedDocumentContent: string = parsedDocuments.structured_format;

  const MIME_LABELS: Record<string, string> = {
    'application/pdf': 'PDF',
    'text/plain': 'Text',
    'text/markdown': 'Markdown',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'Word',
    'application/msword': 'Word',
  };

  const documentNames = input.documents.map(d => d.name);
  const documentTypes = input.documents.map(d => MIME_LABELS[d.type] || d.type);

  // Privacy gate
  const privacyResult = authorizeForModel(
    formattedDocumentContent,
    'DISCOVERY_UPLOAD',
    { projectId: input.projectId, sourceId: `discovery:${input.discoveryType}:${topicSlug}` },
  );

  if (privacyResult.status === 'pending_review') {
    const piiFindings = scanForPii(formattedDocumentContent);
    throw new PrivacyError(
      'Privacy scan detected potential PII in uploaded files',
      piiFindings.map((f: { label: string; snippet: string }) => ({ label: f.label, snippet: f.snippet })),
    );
  }

  if (privacyResult.status === 'denied') {
    throw new Error(`Content authorization failed: ${privacyResult.reason}`);
  }

  // Build template data
  const data: Record<string, unknown> = {
    topic: input.topic,
    effective_topic: input.topic,
    topic_slug: topicSlug,
    project_slug: input.projectSlug,
    project_problem_statement: projectProblemStatement,
    source_intent: input.description,
    description: input.description || input.topic,
    document_content: privacyResult.modelSafeContent!,
    combined_file_content: privacyResult.modelSafeContent!,
    _discovery_type: typeConfig.type,
    selected_study: `discovery-${topicSlug}`,
    study_name: input.topic,
    document_count: input.documents.length,
    document_names: documentNames,
    document_types: documentTypes,
  };

  // Survey-specific fields
  if (input.discoveryType === 'survey_synthesis') {
    data.survey_name = input.surveyName;
    data.question_focus = input.questionFocus || '';
  }

  // Stakeholder-specific fields
  if (input.discoveryType === 'stakeholder_synthesis') {
    data.researcher_contact = input.createdByActorId;
    data.detected_files = input.documents.map(d => d.name).join('\n- ');
    data.file_list = input.documents.map(d => d.name);
  }

  // Artifact identity context
  let contentFingerprint = 'unknown';
  try {
    const { computeContentHash } = require('../helpers/survey');
    contentFingerprint = computeContentHash(privacyResult.modelSafeContent!).substring(0, 16);
  } catch {
    // Fallback if survey module not available
  }
  data.__artifactContext = {
    projectId: input.projectId,
    studyId: null,
    artifactType: 'discovery',
    title: `${input.discoveryType.replace(/_/g, ' ')} — ${input.topic}`,
    canonicalUpstreamInputs: [`content:${contentFingerprint}`],
    createdBy: input.createdByActorId,
  };

  // Process YAML template
  const file = await fetchFileFromRepo(getConfigRepo(), YAML_TEMPLATE_PATH, typeConfig.yaml);
  const variableContext: VariableContext = { projectId: input.projectId };

  const renderedYaml = await processYamlTemplate(
    file.content, data, '', '', false, variableContext,
  );

  let extractionSuccess = true;
  let extractionVariableCount = 0;

  if (renderedYaml.extractionPromise) {
    const extractResult = await renderedYaml.extractionPromise;
    extractionSuccess = extractResult.success;
    extractionVariableCount = extractResult.variableCount || 0;
    if (!extractResult.success) {
      throw new Error(`Cascade variable extraction failed: ${extractResult.error}`);
    }
  }

  return {
    url: renderedYaml.result.url,
    topicSlug,
    typeLabel: typeConfig.label,
    extractionSuccess,
    extractionVariableCount,
  };
}

// ─── Privacy Error ──────────────────────────────────────────────

export class PrivacyError extends Error {
  public readonly findings: PrivacyViolation[];

  constructor(message: string, findings: PrivacyViolation[]) {
    super(message);
    this.name = 'PrivacyError';
    this.findings = findings;
  }
}
