/**
 * Artifact Reconciliation Integration Tests (GOV-2E)
 *
 * Proves:
 * - Class A patch replaces only anchored subject block
 * - Unrelated content byte-equivalent before/after
 * - Missing anchor → manual review (Class D)
 * - Ambiguous anchor → manual review
 * - GitHub issue patched by canonical anchor
 * - No participant_code/prose search
 * - Model-backed artifact → Class C, no write
 * - Artifact public_id preserved
 * - Retry after failed GitHub write succeeds
 * - Rerun after success is idempotent
 * - Reconciliation logs contain no PII
 * - Pre-PH-6D2 artifact becomes manual review
 * - Deterministic re-render blocked when ai_generation_tasks present
 */

import { getTestDb, truncateAll } from './setup/testDb';
import {
  patchAnchoredBlock,
  patchMultipleBlocks,
  classifyArtifact,
  reconcileAffectedArtifacts,
  type ReconciliationResult,
} from '../../services/artifact-reconciliation.service';
import { computeCanonicalAnchor } from '../../services/deep-link.service';
import type { ResearchArtifact } from '../../database/models/research_artifact';
import type { EvidenceConstruct } from '../../database/models/evidence_construct';
import type { AffectedArtifact } from '../../services/dsar-delete.service';

const sequelize = getTestDb();
const ProjectModel = sequelize.models.Project;
const StudyModel = sequelize.models.ResearchStudy;
const ArtifactModel = sequelize.models.ResearchArtifact as typeof ResearchArtifact;
const ConstructModel = sequelize.models.EvidenceConstruct as typeof EvidenceConstruct;
const ArtifactRefModel = sequelize.models.ArtifactEvidenceRef;

// ─── Fixtures ───────────────────────────────────────────────────

async function makeProject(slug: string) {
  return ProjectModel.create({
    name: `P-${slug}`, slug, created_by: 'U_OWNER', status: 'active',
  });
}

async function makeStudy(projectId: number, name: string) {
  return StudyModel.create({
    project_id: projectId, name, channel_name: `ch-${name}`,
    created_by: 'U_OWNER', researcher_name: 'R', researcher_email: 'r@e.com',
  });
}

async function makeConstruct(
  projectId: number, studyId: number, type: string,
  payload: Record<string, unknown>,
) {
  return ConstructModel.create({
    project_id: projectId, study_id: studyId,
    construct_type: type as any, label: `test-${type}`,
    payload, derivation_type: 'model',
    status: 'candidate' as any, created_by: 'U_OWNER',
    stale_due_to_disposition: true,
  });
}

async function makeArtifact(
  projectId: number, studyId: number, templateId: string,
  opts?: { path?: string; url?: string; status?: string; title?: string },
) {
  return ArtifactModel.create({
    project_id: projectId, study_id: studyId,
    template_id: templateId, template_version: '1.0',
    artifact_type: 'readout' as any,
    status: (opts?.status ?? 'written') as any,
    created_by: 'U_OWNER', repo: 'test-repo',
    path: opts?.path ?? `studies/test/${templateId}.md`,
    url: opts?.url ?? `https://github.com/org/repo/blob/main/${templateId}.md`,
    semantic_key: `artifact:${templateId}:${Date.now()}:${Math.random()}`,
    title: opts?.title ?? null,
  });
}

async function makeArtifactRef(artifactId: number, constructId: number) {
  return ArtifactRefModel.create({
    artifact_id: artifactId, construct_id: constructId,
  });
}

/**
 * Build a realistic rendered markdown document with canonical evidence anchors.
 */
function buildRenderedMarkdown(
  constructs: Array<{ publicId: string; displayId: string; label: string; content: string }>,
  extraContent?: string,
): string {
  const lines: string[] = [
    '# Research Readout — Test Study',
    '',
    '## Summary',
    '',
    'This study examined user navigation patterns across 12 participants.',
    '',
    extraContent ?? '',
    '',
    '---',
    '',
    '## Canonical Evidence References',
    '',
  ];

  for (const c of constructs) {
    const anchor = computeCanonicalAnchor(c.publicId);
    lines.push(`<a id="${anchor}"></a>`);
    lines.push('');
    lines.push(`### ${c.displayId} — ${c.label}`);
    lines.push('');
    lines.push(c.content);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by Qori*');

  return lines.join('\n');
}

// ─── Mock GitHub ────────────────────────────────────────────────

function createMockGitHub(contentMap: Map<string, string>) {
  const writes: Array<{ path: string; content: string }> = [];

  return {
    mock: {
      fetchContent: async (repo: string, path: string) => {
        return contentMap.get(path) ?? null;
      },
      writeContent: async (path: string, content: string) => {
        writes.push({ path, content });
        contentMap.set(path, content);
        return { sha: 'new-sha-123', url: `https://github.com/org/repo/blob/main/${path}` };
      },
      fetchIssueBody: async (repo: string, issueNumber: number) => {
        return contentMap.get(`issue:${issueNumber}`) ?? null;
      },
      updateIssueBody: async (repo: string, issueNumber: number, body: string) => {
        writes.push({ path: `issue:${issueNumber}`, content: body });
        contentMap.set(`issue:${issueNumber}`, body);
      },
    },
    writes,
  };
}

// ─── Tests ──────────────────────────────────────────────────────

describe('Artifact Reconciliation (GOV-2E)', () => {
  beforeEach(async () => { await truncateAll(); });
  afterAll(async () => { await sequelize.close(); });

  // ═══════════════════════════════════════════════════════════════
  // CLASS A: DETERMINISTIC PATCH
  // ═══════════════════════════════════════════════════════════════

  describe('Class A — deterministic patch', () => {
    it('replaces only the anchored subject block — unrelated content unchanged', async () => {
      const project = await makeProject('recon-a');
      const study = await makeStudy((project as any).id, 'study-a');

      const targetConstruct = await makeConstruct(
        (project as any).id, (study as any).id, 'finding',
        { finding: 'Users struggle with nav' },
      );
      const unrelatedConstruct = await makeConstruct(
        (project as any).id, (study as any).id, 'finding',
        { finding: 'Search was effective' },
      );

      const artifact = await makeArtifact(
        (project as any).id, (study as any).id, 'research_readout',
        { path: 'studies/test/readout.md' },
      );
      await makeArtifactRef((artifact as any).id, targetConstruct.id);
      await makeArtifactRef((artifact as any).id, unrelatedConstruct.id);

      const originalContent = buildRenderedMarkdown([
        {
          publicId: targetConstruct.public_id,
          displayId: 'F-01', label: 'Navigation Barrier',
          content: 'Participant PT-001 said: "The form was confusing". 8 of 12 participants encountered this issue.',
        },
        {
          publicId: unrelatedConstruct.public_id,
          displayId: 'F-02', label: 'Search Effectiveness',
          content: 'Search functionality was rated highly. Average task completion: 94%.',
        },
      ]);

      const contentMap = new Map([['studies/test/readout.md', originalContent]]);
      const { mock, writes } = createMockGitHub(contentMap);

      const result = await reconcileAffectedArtifacts({
        affectedArtifacts: [{
          artifact_id: (artifact as any).id,
          artifact_public_id: (artifact as any).public_id,
          ref_type: 'reflects',
          via_construct_public_id: targetConstruct.public_id,
        }],
        subjectPublicId: 'test-subject-uuid',
        actorUserId: 'U_OWNER',
        github: mock,
      }, sequelize);

      expect(result.summary.class_a_patched).toBe(1);
      expect(writes).toHaveLength(1);

      const patchedContent = writes[0].content;

      // Target block redacted
      expect(patchedContent).toContain('[REDACTED — DSAR]');
      expect(patchedContent).not.toContain('PT-001');
      expect(patchedContent).not.toContain('The form was confusing');

      // Unrelated block preserved byte-for-byte
      expect(patchedContent).toContain('Search functionality was rated highly. Average task completion: 94%.');
      expect(patchedContent).toContain('F-02 — Search Effectiveness');

      // Header/footer preserved
      expect(patchedContent).toContain('# Research Readout — Test Study');
      expect(patchedContent).toContain('*Generated by Qori*');

      // Target anchor preserved (construct identity)
      const targetAnchor = computeCanonicalAnchor(targetConstruct.public_id);
      expect(patchedContent).toContain(`<a id="${targetAnchor}">`);
    });

    it('unrelated content is byte-equivalent before and after', async () => {
      const project = await makeProject('recon-byte');
      const study = await makeStudy((project as any).id, 'study-byte');

      const targetConstruct = await makeConstruct(
        (project as any).id, (study as any).id, 'finding',
        { finding: 'Issue found' },
      );

      const artifact = await makeArtifact(
        (project as any).id, (study as any).id, 'readout',
        { path: 'studies/test/byte-readout.md' },
      );
      await makeArtifactRef((artifact as any).id, targetConstruct.id);

      const headerSection = '# Test Study Report\n\n## Summary\n\nDetailed analysis of 15 sessions.\n\n';
      const footerSection = '\n---\n\n*Generated by Qori v2.0*\n';

      const originalContent = headerSection +
        '---\n\n## Canonical Evidence References\n\n' +
        `<a id="${computeCanonicalAnchor(targetConstruct.public_id)}"></a>\n\n` +
        '### F-01 — Target Finding\n\n' +
        'Subject-specific content here.\n\n' +
        footerSection;

      const { patched } = patchAnchoredBlock(originalContent, targetConstruct.public_id);

      // Header and footer sections must be byte-identical
      expect(patched.startsWith(headerSection)).toBe(true);
      expect(patched.endsWith(footerSection)).toBe(true);
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // MISSING ANCHOR → MANUAL REVIEW
  // ═══════════════════════════════════════════════════════════════

  describe('missing anchor → manual review', () => {
    it('classifies artifact without anchors as Class D', async () => {
      const project = await makeProject('recon-miss');
      const study = await makeStudy((project as any).id, 'study-miss');

      const construct = await makeConstruct(
        (project as any).id, (study as any).id, 'finding',
        { finding: 'Some finding' },
      );

      const artifact = await makeArtifact(
        (project as any).id, (study as any).id, 'research_readout',
        { path: 'studies/test/no-anchors.md' },
      );
      await makeArtifactRef((artifact as any).id, construct.id);

      // Content without any ev- anchors
      const noAnchorContent = '# Readout\n\n## Findings\n\nSome findings here.\n';
      const contentMap = new Map([['studies/test/no-anchors.md', noAnchorContent]]);
      const { mock } = createMockGitHub(contentMap);

      const result = await reconcileAffectedArtifacts({
        affectedArtifacts: [{
          artifact_id: (artifact as any).id,
          artifact_public_id: (artifact as any).public_id,
          ref_type: 'reflects',
          via_construct_public_id: construct.public_id,
        }],
        subjectPublicId: 'test-subject',
        actorUserId: 'U_OWNER',
        github: mock,
      }, sequelize);

      // With template_id → Class C (would need LLM)
      expect(result.summary.class_c_manual).toBe(1);
      expect(result.manual_review).toHaveLength(1);
      expect(result.manual_review[0].reason).toContain('LLM');
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // AMBIGUOUS ANCHOR → MANUAL REVIEW
  // ═══════════════════════════════════════════════════════════════

  describe('ambiguous anchor → patchAnchoredBlock returns not found', () => {
    it('returns found=false when anchor exists but heading is missing', () => {
      const publicId = 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee';
      const anchor = computeCanonicalAnchor(publicId);
      // Anchor exists but no ### heading follows
      const content = `Some text\n<a id="${anchor}"></a>\nNo heading here\n`;

      const { found } = patchAnchoredBlock(content, publicId);
      expect(found).toBe(false);
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // GITHUB ISSUE PATCHED BY CANONICAL ANCHOR
  // ═══════════════════════════════════════════════════════════════

  describe('GitHub issue patch by canonical anchor', () => {
    it('patches issue body using ev-{uuid} anchor', () => {
      const publicId = '11111111-2222-3333-4444-555555555555';
      const anchor = computeCanonicalAnchor(publicId);

      const issueBody = [
        '## Design Ticket',
        '',
        `<a id="${anchor}"></a>`,
        '',
        '### DT-001 — Fix navigation',
        '',
        'Based on participant feedback: "The menu was hidden"',
        '',
        '## Implementation Notes',
        '',
        'Use sidebar pattern.',
      ].join('\n');

      const { patched, found } = patchAnchoredBlock(issueBody, publicId);

      expect(found).toBe(true);
      expect(patched).toContain('[REDACTED — DSAR]');
      expect(patched).not.toContain('The menu was hidden');
      // Implementation notes preserved
      expect(patched).toContain('Use sidebar pattern.');
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // NO PARTICIPANT_CODE / PROSE SEARCH
  // ═══════════════════════════════════════════════════════════════

  describe('no participant_code/prose search', () => {
    it('does not find or patch content by participant code — only by anchor', () => {
      const publicId = 'aaaaaaaa-bbbb-cccc-dddd-111111111111';

      // Content mentions PT-001 but WITHOUT canonical anchor
      const content = [
        '# Readout',
        '',
        '## Findings',
        '',
        '### F-01 — Navigation Issue',
        '',
        'PT-001 said: "The form was confusing"',
        '',
      ].join('\n');

      const { patched, found } = patchAnchoredBlock(content, publicId);

      // NOT found because there's no anchor — even though PT-001 text exists
      expect(found).toBe(false);
      expect(patched).toBe(content); // Unchanged
      expect(patched).toContain('PT-001'); // Still there — no prose matching
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // MODEL-BACKED ARTIFACT → CLASS C, NO WRITE
  // ═══════════════════════════════════════════════════════════════

  describe('model-backed artifact → Class C', () => {
    it('classifies template-based artifact without anchors as Class C — no GitHub write', async () => {
      const project = await makeProject('recon-c');
      const study = await makeStudy((project as any).id, 'study-c');

      const construct = await makeConstruct(
        (project as any).id, (study as any).id, 'theme',
        { theme_name: 'Test' },
      );

      const artifact = await makeArtifact(
        (project as any).id, (study as any).id, 'affinity_mapping',
        { path: 'studies/test/synthesis.md' },
      );
      await makeArtifactRef((artifact as any).id, construct.id);

      // Content exists but no anchors for this construct
      const contentMap = new Map([
        ['studies/test/synthesis.md', '# Synthesis\n\n## Themes\n\nTheme analysis here.\n'],
      ]);
      const { mock, writes } = createMockGitHub(contentMap);

      const result = await reconcileAffectedArtifacts({
        affectedArtifacts: [{
          artifact_id: (artifact as any).id,
          artifact_public_id: (artifact as any).public_id,
          ref_type: 'reflects',
          via_construct_public_id: construct.public_id,
        }],
        subjectPublicId: 'test-subject',
        actorUserId: 'U_OWNER',
        github: mock,
      }, sequelize);

      expect(result.summary.class_c_manual).toBe(1);
      expect(writes).toHaveLength(0); // NO GitHub write
      expect(result.manual_review).toHaveLength(1);
      expect(result.manual_review[0].reason).toContain('ai_generation_tasks');
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // ARTIFACT PUBLIC_ID PRESERVED
  // ═══════════════════════════════════════════════════════════════

  describe('artifact public_id preserved', () => {
    it('does not create a new artifact — same public_id after patch', async () => {
      const project = await makeProject('recon-id');
      const study = await makeStudy((project as any).id, 'study-id');

      const construct = await makeConstruct(
        (project as any).id, (study as any).id, 'finding',
        { finding: 'test' },
      );

      const artifact = await makeArtifact(
        (project as any).id, (study as any).id, 'research_readout',
        { path: 'studies/test/id-readout.md' },
      );
      const originalPublicId = (artifact as any).public_id;
      await makeArtifactRef((artifact as any).id, construct.id);

      const content = buildRenderedMarkdown([
        { publicId: construct.public_id, displayId: 'F-01', label: 'Test', content: 'Subject data' },
      ]);
      const contentMap = new Map([['studies/test/id-readout.md', content]]);
      const { mock } = createMockGitHub(contentMap);

      await reconcileAffectedArtifacts({
        affectedArtifacts: [{
          artifact_id: (artifact as any).id,
          artifact_public_id: originalPublicId,
          ref_type: 'reflects',
          via_construct_public_id: construct.public_id,
        }],
        subjectPublicId: 'test-subject',
        actorUserId: 'U_OWNER',
        github: mock,
      }, sequelize);

      // Verify same artifact — no new records created
      const totalArtifacts = await ArtifactModel.count({
        where: { project_id: (project as any).id },
      });
      expect(totalArtifacts).toBe(1);

      const updated = await ArtifactModel.findByPk((artifact as any).id);
      expect(updated!.public_id).toBe(originalPublicId);
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // RETRY AFTER FAILED GITHUB WRITE
  // ═══════════════════════════════════════════════════════════════

  describe('retry after failed GitHub write succeeds', () => {
    it('retries failed write and succeeds on second run', async () => {
      const project = await makeProject('recon-retry');
      const study = await makeStudy((project as any).id, 'study-retry');

      const construct = await makeConstruct(
        (project as any).id, (study as any).id, 'finding',
        { finding: 'test' },
      );

      const artifact = await makeArtifact(
        (project as any).id, (study as any).id, 'research_readout',
        { path: 'studies/test/retry-readout.md' },
      );
      await makeArtifactRef((artifact as any).id, construct.id);

      const content = buildRenderedMarkdown([
        { publicId: construct.public_id, displayId: 'F-01', label: 'Test', content: 'Data' },
      ]);
      const contentMap = new Map([['studies/test/retry-readout.md', content]]);

      // First attempt: write fails
      let writeAttempt = 0;
      const failingMock = {
        fetchContent: async (repo: string, path: string) => contentMap.get(path) ?? null,
        writeContent: async (path: string, content: string) => {
          writeAttempt++;
          if (writeAttempt === 1) throw new Error('GitHub API timeout');
          contentMap.set(path, content);
          return { sha: 'new-sha', url: `https://github.com/org/repo/blob/main/${path}` };
        },
        fetchIssueBody: async () => null,
        updateIssueBody: async () => {},
      };

      const affected: AffectedArtifact[] = [{
        artifact_id: (artifact as any).id,
        artifact_public_id: (artifact as any).public_id,
        ref_type: 'reflects',
        via_construct_public_id: construct.public_id,
      }];

      // First run: fails
      const first = await reconcileAffectedArtifacts({
        affectedArtifacts: affected,
        subjectPublicId: 'test-subject',
        actorUserId: 'U_OWNER',
        github: failingMock,
      }, sequelize);
      expect(first.summary.failed).toBe(1);

      // Second run: succeeds
      const second = await reconcileAffectedArtifacts({
        affectedArtifacts: affected,
        subjectPublicId: 'test-subject',
        actorUserId: 'U_OWNER',
        github: failingMock,
      }, sequelize);
      expect(second.summary.class_a_patched).toBe(1);
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // IDEMPOTENT RERUN
  // ═══════════════════════════════════════════════════════════════

  describe('rerun after success is idempotent', () => {
    it('returns already_reconciled on second run — no duplicate edits', async () => {
      const project = await makeProject('recon-idem');
      const study = await makeStudy((project as any).id, 'study-idem');

      const construct = await makeConstruct(
        (project as any).id, (study as any).id, 'finding',
        { finding: 'test' },
      );

      const artifact = await makeArtifact(
        (project as any).id, (study as any).id, 'research_readout',
        { path: 'studies/test/idem-readout.md' },
      );
      await makeArtifactRef((artifact as any).id, construct.id);

      const content = buildRenderedMarkdown([
        { publicId: construct.public_id, displayId: 'F-01', label: 'Test', content: 'Subject data' },
      ]);
      const contentMap = new Map([['studies/test/idem-readout.md', content]]);
      const { mock, writes } = createMockGitHub(contentMap);

      const affected: AffectedArtifact[] = [{
        artifact_id: (artifact as any).id,
        artifact_public_id: (artifact as any).public_id,
        ref_type: 'reflects',
        via_construct_public_id: construct.public_id,
      }];

      // First run: patches
      const first = await reconcileAffectedArtifacts({
        affectedArtifacts: affected,
        subjectPublicId: 'test-subject',
        actorUserId: 'U_OWNER',
        github: mock,
      }, sequelize);
      expect(first.summary.class_a_patched).toBe(1);
      expect(writes).toHaveLength(1);

      // Second run: already reconciled — no new write
      const second = await reconcileAffectedArtifacts({
        affectedArtifacts: affected,
        subjectPublicId: 'test-subject',
        actorUserId: 'U_OWNER',
        github: mock,
      }, sequelize);
      expect(second.summary.already_reconciled).toBe(1);
      expect(writes).toHaveLength(1); // Still only 1 write total
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // RECONCILIATION LOGS CONTAIN NO PII
  // ═══════════════════════════════════════════════════════════════

  describe('reconciliation logs contain no PII', () => {
    it('records contain only public_ids and outcome — no names, codes, or quotes', async () => {
      const project = await makeProject('recon-pii');
      const study = await makeStudy((project as any).id, 'study-pii');

      const construct = await makeConstruct(
        (project as any).id, (study as any).id, 'finding',
        { finding: 'Participant John said navigation was broken' },
      );

      const artifact = await makeArtifact(
        (project as any).id, (study as any).id, 'research_readout',
        { path: 'studies/test/pii-readout.md' },
      );
      await makeArtifactRef((artifact as any).id, construct.id);

      const content = buildRenderedMarkdown([
        {
          publicId: construct.public_id,
          displayId: 'F-01', label: 'Nav Issue',
          content: 'PT-001 (John Doe) said: "The navigation was terrible"',
        },
      ]);
      const contentMap = new Map([['studies/test/pii-readout.md', content]]);
      const { mock } = createMockGitHub(contentMap);

      const result = await reconcileAffectedArtifacts({
        affectedArtifacts: [{
          artifact_id: (artifact as any).id,
          artifact_public_id: (artifact as any).public_id,
          ref_type: 'reflects',
          via_construct_public_id: construct.public_id,
        }],
        subjectPublicId: 'test-subject',
        actorUserId: 'U_OWNER',
        github: mock,
      }, sequelize);

      const recordStr = JSON.stringify(result.records);
      expect(recordStr).not.toContain('John');
      expect(recordStr).not.toContain('PT-001');
      expect(recordStr).not.toContain('navigation was terrible');
      expect(recordStr).not.toContain('John Doe');

      // Does contain public_ids and outcome
      expect(recordStr).toContain(construct.public_id);
      expect(recordStr).toContain('patched');
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // PRE-PH-6D2 ARTIFACT → MANUAL REVIEW
  // ═══════════════════════════════════════════════════════════════

  describe('pre-PH-6D2 artifact → manual review', () => {
    it('artifact without template_id becomes Class D', async () => {
      const project = await makeProject('recon-pre');
      const study = await makeStudy((project as any).id, 'study-pre');

      const construct = await makeConstruct(
        (project as any).id, (study as any).id, 'finding',
        { finding: 'old finding' },
      );

      // Artifact with no template_id (pre-PH-6D2)
      const artifact = await ArtifactModel.create({
        project_id: (project as any).id, study_id: (study as any).id,
        template_id: '', template_version: '',
        artifact_type: 'readout' as any, status: 'written' as any,
        created_by: 'U_OWNER', repo: 'test-repo',
        path: 'old/readout.md',
        semantic_key: `old:${Date.now()}`,
      });
      await makeArtifactRef((artifact as any).id, construct.id);

      // Content without anchors (pre-PH-6D2)
      const contentMap = new Map([
        ['old/readout.md', '# Old Readout\n\nSome legacy content.\n'],
      ]);
      const { mock } = createMockGitHub(contentMap);

      const result = await reconcileAffectedArtifacts({
        affectedArtifacts: [{
          artifact_id: (artifact as any).id,
          artifact_public_id: (artifact as any).public_id,
          ref_type: 'reflects',
          via_construct_public_id: construct.public_id,
        }],
        subjectPublicId: 'test-subject',
        actorUserId: 'U_OWNER',
        github: mock,
      }, sequelize);

      expect(result.summary.class_d_manual).toBe(1);
      expect(result.manual_review).toHaveLength(1);
      expect(result.manual_review[0].reason).toContain('pre-PH-6D2');
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // CLASSIFICATION UNIT TESTS
  // ═══════════════════════════════════════════════════════════════

  describe('classifyArtifact', () => {
    it('returns A when anchors present in content', () => {
      const publicId = 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee';
      const anchor = computeCanonicalAnchor(publicId);
      const content = `# Doc\n<a id="${anchor}"></a>\n### F-01\nData\n`;

      const artifact = {
        path: 'test.md', url: 'https://example.com/test.md',
        template_id: 'research_readout',
      } as ResearchArtifact;

      expect(classifyArtifact(artifact, [publicId], content)).toBe('A');
    });

    it('returns C when template exists but no anchors', () => {
      const artifact = {
        path: 'test.md', url: 'https://example.com/test.md',
        template_id: 'research_readout',
      } as ResearchArtifact;

      expect(classifyArtifact(artifact, ['some-uuid'], '# No anchors here')).toBe('C');
    });

    it('returns D when no template and no anchors', () => {
      const artifact = {
        path: 'test.md', url: 'https://example.com/test.md',
        template_id: '',
      } as ResearchArtifact;

      expect(classifyArtifact(artifact, ['some-uuid'], '# No anchors here')).toBe('D');
    });

    it('returns D when content is null', () => {
      const artifact = {
        path: 'test.md', url: 'https://example.com/test.md',
        template_id: 'research_readout',
      } as ResearchArtifact;

      expect(classifyArtifact(artifact, ['some-uuid'], null)).toBe('D');
    });

    it('returns D when no path and no url', () => {
      const artifact = {
        path: null, url: null, template_id: 'research_readout',
      } as unknown as ResearchArtifact;

      expect(classifyArtifact(artifact, ['some-uuid'], '# Content')).toBe('D');
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // MULTIPLE CONSTRUCTS ON SAME ARTIFACT
  // ═══════════════════════════════════════════════════════════════

  describe('multiple constructs on same artifact', () => {
    it('patches all affected anchored blocks in one pass', async () => {
      const project = await makeProject('recon-multi');
      const study = await makeStudy((project as any).id, 'study-multi');

      const c1 = await makeConstruct((project as any).id, (study as any).id, 'finding', { finding: 'f1' });
      const c2 = await makeConstruct((project as any).id, (study as any).id, 'finding', { finding: 'f2' });
      const cKeep = await makeConstruct((project as any).id, (study as any).id, 'finding', { finding: 'keep' });

      const artifact = await makeArtifact(
        (project as any).id, (study as any).id, 'research_readout',
        { path: 'studies/test/multi.md' },
      );
      await makeArtifactRef((artifact as any).id, c1.id);
      await makeArtifactRef((artifact as any).id, c2.id);
      await makeArtifactRef((artifact as any).id, cKeep.id);

      const content = buildRenderedMarkdown([
        { publicId: c1.public_id, displayId: 'F-01', label: 'First', content: 'Data 1' },
        { publicId: c2.public_id, displayId: 'F-02', label: 'Second', content: 'Data 2' },
        { publicId: cKeep.public_id, displayId: 'F-03', label: 'Third', content: 'Keep this data' },
      ]);
      const contentMap = new Map([['studies/test/multi.md', content]]);
      const { mock, writes } = createMockGitHub(contentMap);

      const result = await reconcileAffectedArtifacts({
        affectedArtifacts: [
          { artifact_id: (artifact as any).id, artifact_public_id: (artifact as any).public_id, ref_type: 'reflects', via_construct_public_id: c1.public_id },
          { artifact_id: (artifact as any).id, artifact_public_id: (artifact as any).public_id, ref_type: 'reflects', via_construct_public_id: c2.public_id },
        ],
        subjectPublicId: 'test-subject',
        actorUserId: 'U_OWNER',
        github: mock,
      }, sequelize);

      expect(result.summary.class_a_patched).toBe(1); // One artifact, one patch operation
      expect(writes).toHaveLength(1);

      const patched = writes[0].content;
      // Both affected blocks redacted
      expect(patched).not.toContain('Data 1');
      expect(patched).not.toContain('Data 2');
      // Unaffected block preserved
      expect(patched).toContain('Keep this data');
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // EMPTY AFFECTED ARTIFACTS
  // ═══════════════════════════════════════════════════════════════

  describe('empty affected artifacts', () => {
    it('returns empty result with no errors', async () => {
      const result = await reconcileAffectedArtifacts({
        affectedArtifacts: [],
        subjectPublicId: 'test-subject',
        actorUserId: 'U_OWNER',
      }, sequelize);

      expect(result.records).toHaveLength(0);
      expect(result.manual_review).toHaveLength(0);
      expect(result.summary.class_a_patched).toBe(0);
    });
  });
});
